#!/usr/bin/env python3
"""patch_battery_ads7830.py — Replace INA219 with ADS7830 battery monitor."""

TARGET = "/home/tony1/Tony_the_Bot/stream_server.py"

with open(TARGET, "r", encoding="utf-8") as f:
    src = f.read()

original = src

# ── 1. Replace INA219 import block + battery config with ADS7830 ──────────
old_battery_imports = (
    "# INA219 battery monitor — optional, graceful fallback if not connected\n"
    "try:\n"
    "    from ina219 import INA219, DeviceRangeError\n"
    "    INA219_AVAILABLE = True\n"
    "    SHUNT_OHMS = 0.1\n"
    "    # 4x 18650 in series: 16.8V full, 12.0V empty\n"
    "    BATTERY_MAX_V = 16.8\n"
    "    BATTERY_MIN_V = 12.0\n"
    "except ImportError:\n"
    "    INA219_AVAILABLE = False\n"
    "\n"
    "# ── BATTERY CONFIG ──\n"
    "BATTERY_CAPACITY_MAH = 10000   # 4× 2500 mAh — adjust to your actual pack\n"
    "# 4S 18650 open-circuit voltage → SoC lookup table (no-load, room temp)\n"
    "SOC_CURVE = [\n"
    "    (16.80, 100.0), (16.40, 90.0), (16.00, 80.0), (15.60, 70.0),\n"
    "    (15.20,  60.0), (14.80, 50.0), (14.40, 40.0), (14.00, 30.0),\n"
    "    (13.60,  20.0), (13.20, 10.0), (12.80,  5.0), (12.00,  0.0),\n"
    "]"
)
new_battery_imports = (
    "# ── ADS7830 battery monitor (Freenove board at 0x48, I2C bus 1) ──────────\n"
    "import smbus as _smbus_mod\n"
    "try:\n"
    "    _adc_bus = _smbus_mod.SMBus(1)\n"
    "    ADC_AVAILABLE = True\n"
    "except Exception:\n"
    "    _adc_bus = None\n"
    "    ADC_AVAILABLE = False\n"
    "\n"
    "ADC_ADDR  = 0x48\n"
    "ADC_COEFF = 3        # Freenove voltage divider coefficient\n"
    "\n"
    "def _adc_read_channel(ch):\n"
    "    \"\"\"Read ADS7830 channel using Freenove command formula.\"\"\"\n"
    "    cmd = 0x84 | ((((ch << 2) | (ch >> 1)) & 0x07) << 4)\n"
    "    _adc_bus.write_byte(ADC_ADDR, cmd)\n"
    "    import time as _t; _t.sleep(0.01)\n"
    "    v1 = _adc_bus.read_byte(ADC_ADDR)\n"
    "    v2 = _adc_bus.read_byte(ADC_ADDR)\n"
    "    raw = v1 if v1 == v2 else (v1 + v2) // 2\n"
    "    return round(raw / 255.0 * 5 * ADC_COEFF, 2)\n"
    "\n"
    "def read_battery_voltages():\n"
    "    \"\"\"Return (bat1_v, bat2_v) or (None, None) on error.\"\"\"\n"
    "    if not ADC_AVAILABLE:\n"
    "        return None, None\n"
    "    try:\n"
    "        return _adc_read_channel(0), _adc_read_channel(4)\n"
    "    except Exception:\n"
    "        return None, None\n"
    "\n"
    "# ── BATTERY CONFIG — 2S 18650 pack ───────────────────────────────────────\n"
    "BATTERY_CAPACITY_MAH = 5000    # 2× 2500 mAh 18650 cells\n"
    "# 2S 18650 open-circuit voltage → SoC lookup (no-load, room temp)\n"
    "SOC_CURVE = [\n"
    "    (8.40, 100.0), (8.20, 95.0), (8.00, 88.0), (7.80, 78.0),\n"
    "    (7.60,  65.0), (7.40, 50.0), (7.20, 35.0), (7.00, 20.0),\n"
    "    (6.80,  10.0), (6.40,  5.0), (6.00,  0.0),\n"
    "]"
)
assert old_battery_imports in src, "FAIL: battery imports block not found"
src = src.replace(old_battery_imports, new_battery_imports, 1)

# ── 2. Replace battery_poll_loop ─────────────────────────────────────────
old_poll = (
    "def battery_poll_loop():\n"
    "    \"\"\"Sample INA219 every 10 s and store to battery_history for charting.\"\"\"\n"
    "    while True:\n"
    "        if INA219_AVAILABLE:\n"
    "            try:\n"
    "                ina = INA219(SHUNT_OHMS)\n"
    "                ina.configure()\n"
    "                v = ina.voltage()\n"
    "                try:\n"
    "                    i = ina.current()\n"
    "                except DeviceRangeError:\n"
    "                    i = None\n"
    "                soc = voltage_to_soc(v)\n"
    "                w   = round(v * (i / 1000), 2) if i is not None else None\n"
    "                with battery_history_lock:\n"
    "                    battery_history.append({\n"
    "                        \"t\":   __import__('datetime').datetime.now().strftime(\"%H:%M:%S\"),\n"
    "                        \"v\":   round(v, 2),\n"
    "                        \"i\":   round(i, 1) if i is not None else None,\n"
    "                        \"w\":   w,\n"
    "                        \"pct\": soc,\n"
    "                    })\n"
    "            except Exception:\n"
    "                pass\n"
    "        time.sleep(10)"
)
new_poll = (
    "def battery_poll_loop():\n"
    "    \"\"\"Sample ADS7830 every 10 s and store to battery_history for charting.\"\"\"\n"
    "    while True:\n"
    "        if ADC_AVAILABLE:\n"
    "            try:\n"
    "                v1, v2 = read_battery_voltages()\n"
    "                if v2 is not None:\n"
    "                    soc = voltage_to_soc(v2)\n"
    "                    with battery_history_lock:\n"
    "                        battery_history.append({\n"
    "                            \"t\":   datetime.now().strftime(\"%H:%M:%S\"),\n"
    "                            \"v\":   v2,\n"
    "                            \"v1\":  v1,\n"
    "                            \"pct\": soc,\n"
    "                        })\n"
    "            except Exception:\n"
    "                pass\n"
    "        time.sleep(10)"
)
assert old_poll in src, "FAIL: battery_poll_loop not found"
src = src.replace(old_poll, new_poll, 1)

# ── 3. Replace /power route INA219 section ───────────────────────────────
old_power_route = (
    "    # --- INA219 battery reading (when hardware is connected) ---\n"
    "    if INA219_AVAILABLE:\n"
    "        try:\n"
    "            ina = INA219(SHUNT_OHMS)\n"
    "            ina.configure()\n"
    "            voltage = ina.voltage()\n"
    "            try:\n"
    "                current = ina.current()\n"
    "            except DeviceRangeError:\n"
    "                current = None\n"
    "            soc     = voltage_to_soc(voltage)\n"
    "            power_w = round(voltage * (current / 1000), 2) if current is not None else None\n"
    "            runtime = estimate_runtime(soc, current)\n"
    "            result[\"voltage\"]     = round(voltage, 2)\n"
    "            result[\"current_ma\"]  = round(current, 1) if current is not None else None\n"
    "            result[\"battery_pct\"] = soc\n"
    "            result[\"power_w\"]     = power_w\n"
    "            result[\"runtime_min\"] = runtime\n"
    "            result[\"source\"] = \"charging\" if (current and current > 50) else \"battery\"\n"
    "        except Exception:\n"
    "            pass"
)
new_power_route = (
    "    # --- ADS7830 battery reading ---\n"
    "    if ADC_AVAILABLE:\n"
    "        try:\n"
    "            v1, v2 = read_battery_voltages()\n"
    "            if v2 is not None:\n"
    "                soc     = voltage_to_soc(v2)\n"
    "                runtime = estimate_runtime(soc, 500)  # assume ~500mA draw\n"
    "                result[\"voltage\"]     = v2\n"
    "                result[\"voltage_cell\"] = v1\n"
    "                result[\"battery_pct\"] = soc\n"
    "                result[\"runtime_min\"] = runtime\n"
    "                result[\"source\"]      = \"battery\"\n"
    "        except Exception:\n"
    "            pass"
)
assert old_power_route in src, "FAIL: /power INA219 section not found"
src = src.replace(old_power_route, new_power_route, 1)

assert src != original, "FAIL: no changes made"
with open(TARGET, "w", encoding="utf-8") as f:
    f.write(src)

print("OK: ADS7830 battery monitor patched successfully")
